version: '3'

services:
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./MovieFusion:/MovieFusion
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database: 
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./MovieFusion:/MovieFusion

    links: 
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./MovieFusion:/MovieFusion

    links: 
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - database