# Generated by Django 4.2.5 on 2023-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
