# Generated by Django 4.2.5 on 2023-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_director_movie_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
