# Generated by Django 4.2.5 on 2023-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
